name: python-315

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
  pull_request:
    branches:
      - main
      - '3.15'
  push:
    branches:
      - main
      - '3.15'

permissions:
  contents: read

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      tx_project: python-newest
      version: 3.15
    secrets: inherit
  check:
    uses: ./.github/workflows/check.yml
    needs: sync
    with:
      tx_project: python-newest
      version: 3.15
    secrets: inherit
