name: python-39

on:
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    permissions:
      contents: write
    with:
      tx_project: ${{ github.workflow }}
      version: 3.9
    secrets:
      tx_token: ${{ secrets.TX_TOKEN }}
  check:
    uses: ./.github/workflows/check.yml
    permissions:
      contents: read
    needs: sync
    with:
      tx_project: ${{ github.workflow }}
      version: 3.9
    secrets:
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
      telegram_to: ${{ secrets.TELEGRAM_TO }}
