name: python-39

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      tx_project: ${{ github.workflow }}
      version: 3.9
    secrets: inherit
  check:
    uses: ./.github/workflows/check.yml
    needs: sync
    with:
      tx_project: ${{ github.workflow }}
      version: 3.9
    secrets: inherit
