name: python-313

on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'
  pull_request:
    branches:
      - main
      - '3.13'
  push:
    branches:
      - main
      - '3.13'

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    permissions:
      contents: write
    with:
      tx_project: ${{ github.workflow }}
      version: 3.13
    secrets:
      tx_token: ${{ secrets.TX_TOKEN }}
  check:
    uses: ./.github/workflows/check.yml
    permissions:
      contents: read
    needs: sync
    with:
      tx_project: ${{ github.workflow }}
      version: 3.13
    secrets:
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
      telegram_to: ${{ secrets.TELEGRAM_TO }}
