name: python-315

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
  pull_request:
    branches:
      - main
      - '3.15'
  push:
    branches:
      - main
      - '3.15'


jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    permissions:
      contents: write
    with:
      tx_project: python-newest
      version: 3.15
    secrets:
      tx_token: ${{ secrets.TX_TOKEN }}
  check:
    uses: ./.github/workflows/check.yml
    permissions:
      contents: read
    needs: sync
    with:
      tx_project: python-newest
      version: 3.15
    secrets:
      telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
      telegram_to: ${{ secrets.TELEGRAM_TO }}
